### ISSUE TITLE
Issue in dark mode.

### ISSUE THREAD

**Issue by eramrit78** [yurkinh/Plugin.Maui.Calendar#1]
great plugin.

I have check in light and dark mode. in light mode work perfect but in dark mode not showing days properly.
Thanks
![Screenshot_1693318101](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/48124576/09dd7043-3b3d-499c-ab99-1c09951fbcd1)

**Comment by eramrit78** [comment]
any update?

**Comment by yurkinh** [comment]
Hello @eramrit78 
I have updated SimplePage DaysTitleColor. Now it responds to Dar/Light theme.
Check SimplPage and App.Xaml.cs changes
Simple Page
`        DaysTitleColor = "{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource Yellow100Accent}}"
`
AppXaml.cs
`  
    protected override void OnResume()
    {
        AppTheme currentTheme = Application.Current.RequestedTheme;        
    }
`
