### ISSUE TITLE
[Suggestion] Remove SwipeAwareContainer

### ISSUE THREAD

**Issue by FabriBertani** [yurkinh/Plugin.Maui.Calendar#10]
Hi @yurkinh, thank you for porting this plugin.

I would like to suggest the removal of the `SwipeAwareContainer` in favour of the `SwipeGestures` included in .Net MAUI.

The change will be to use a simple layout that wraps the `MonthDaysView` in the `Calendar` that also contains the gestures and let the framework and the platform handle the subscriptions, something like this:

```xml
<VerticalStackLayout>
    <VerticalStackLayout.GestureRecognizers>
        <SwipeGestureRecognizer
            Direction="Left"
            Swiped="OnSwipedLeft" />
        <SwipeGestureRecognizer
            Direction="Right"
            Swiped="OnSwipedRight" />
        <SwipeGestureRecognizer
            Direction="Up"
            Swiped="OnSwipedUp" />
    </VerticalStackLayout.GestureRecognizers>
    
    <controls:MonthDaysView
        ...
        TodayOutlineColor="{Binding TodayOutlineColor, Source={x:Reference calendar}}" />
</VerticalStackLayout>
```
And change the code behind handlers to receive a `SwipedEventArgs`, instead of `EventArgs`:

```csharp
private void OnSwipedRight(object sender, SwipedEventArgs e)
{
    SwipeRightCommand?.Execute(null);

    if (SwipeToChangeMonthEnabled)
        PrevUnit();
}

private void OnSwipedLeft(object sender, SwipedEventArgs e)
{
    SwipeLeftCommand?.Execute(null);

    if (SwipeToChangeMonthEnabled)
        NextUnit();
}

private void OnSwipedUp(object sender, SwipedEventArgs e)
{
    SwipeUpCommand?.Execute(null);

    if (SwipeUpToHideEnabled)
        ToggleCalendarSectionVisibility();
}
```

I've tried and it works the same as the container class.

Thank you!

**Comment by yurkinh** [comment]
Hi @FabriBertani 
Good point.
Thanks for the provided code samples 
Yesterday I have fixed `DisableSwipeDetection` which was ignored.
I will take a look at it today

**Comment by yurkinh** [comment]
I have moved GestureRecognizers to the MonthDaysView cause it is also ContentView no need for an additional vertical stacklayout. Also removed SwipeAwarecontainer.
Check please the latest 1.0.10 Nuget version.
Thanks for the suggestion!
