### ISSUE TITLE
Initialize Events with your data and a different dot color per day PROBLEM!

### ISSUE THREAD

**Issue by Kiriakos41** [yurkinh/Plugin.Maui.Calendar#101]
![image](https://github.com/user-attachments/assets/cb59b311-6c02-4565-a9d3-0e14c2608fb9)

_.Net MAUI_

**If I try to add colors to the collection, I get an error message.**

_using Plugin.Maui.Calendar.Models;_

**Comment by MykhailoDav** [comment]
Hi @Kiriakos41, take a look at the AdvancedPageViewModel in the SampleApp, there is the code you are looking for:
```c#
[DateTime.Now.AddDays(-6)] = new DayEventCollection<AdvancedEventModel>(Colors.Purple, Colors.Purple)
{
    new() { Name = "Cool event1", Description = "This is Cool event1's description!", Starting= new DateTime() },
    new() { Name = "Cool event2", Description = "This is Cool event2's description!", Starting= new DateTime() }
}
```

**Comment by Kiriakos41** [comment]
i copy paste the entire DayModel from your samples and is working
