### ISSUE TITLE
Calendar DayEventCollection Colors

### ISSUE THREAD

**Issue by Kiriakos41** [yurkinh/Plugin.Maui.Calendar#104]
I want to show on my calendar the 3 dots with this colors:

`Colors = [Colors.Orange, Colors.Green, Colors.Red]`

but is showing every time on the calendar the first dot as purple, how can i remove the purple one?
**My Code:**
    var threeEventsTommorrow = GenerateEvents(3, "Simple3").ToArray();

    var dayEventCollection = new DayEventCollection<EventModel>
    {
        Colors = [Colors.Orange, Colors.Green, Colors.Red],
    };

    foreach (var eventItem in threeEventsTommorrow)
    {
        dayEventCollection.Add(eventItem);

    }

    Events.Add(DateTime.Now.AddDays(1), dayEventCollection);
    }
```

private static IEnumerable<EventModel> GenerateEvents(int count, string name)
{
    return Enumerable.Range(1, count).Select(x => new EventModel
    {
        Description = $"This is {name} event{x}'s description!",
    });
}
```

Photo:
![image](https://github.com/user-attachments/assets/f8247397-f890-475d-be6c-cc8bb8c0da04)

**Comment by Haukinger** [comment]
The color from the first event of a day, right now, is taken from the event itself.

We could add `EventColors != null && EventColors.Count >= 1 ? EventColors[ 0 ] : ` to `DayModel.EventColor` to make `Colors` take precedence if present.
