### ISSUE TITLE
Days not showing after navigate to another page

### ISSUE THREAD

**Issue by criss02-cs** [yurkinh/Plugin.Maui.Calendar#13]
Sorry again if I create another issue for you but I need this plugin.
I don't know if it's due to the latest updates but now when I go to another page from the page where the Calendar component is present and then go back it no longer shows me the days of the month, only dots remain. I have attached a video where I show the problem.
The culture that I set is it-IT

https://github.com/yurkinh/Plugin.Maui.Calendar/assets/52246268/4b76c83a-86e2-46e7-8a7c-df4082bb2114

**Comment by yurkinh** [comment]
I think that's because of the new disposing method which fires in the Unload event.
I will take a look at it today

**Comment by yurkinh** [comment]
Hi @criss02-cs 
Check please the latest version 1.1.1.
I have fixed issue with disposing

**Comment by criss02-cs** [comment]
Hi @yurkinh 
It works thanks. Appreciate that
