### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by AndyG74** [yurkinh/Plugin.Maui.Calendar#15]
Visual Studio: 17.8.3
Plugin.Maui.Calendar: 1.1.1

i get this unhandled exeption on open a new page that contains the calender control.

![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/61390650/8eb34b71-b942-473d-870b-ab96600b50a3)

the xaml-code ist pretty simple

![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/61390650/42dc9db0-4bd1-4724-b0fe-d59b00c88878)

the code below open the page and produced the exception

![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/61390650/a27524a2-d89e-4ec8-8f01-7375cb1906a1)

**Comment by yurkinh** [comment]
Hi @AndyG74 
Thanks for reporting this issue.
I will take a look at it

**Comment by yurkinh** [comment]
Can you provide a sample?
And the environment that you have used (Device or emulator). Cause  I was not able to reproduce this issue.
It just loads calendar with default styles.
![Screenshot 2024-01-10 at 17 55 55](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/17849938/6eafcd3a-827f-4fb8-9353-f3be601a51cb)

**Comment by AndyG74** [comment]
if i create a new blank project then it's working without exception on android-device and android-emulator. only in my existing project the exception is raising.

**Comment by yurkinh** [comment]
Can you provide a sample or at least some extended stacktrace?
