### ISSUE TITLE
Events Don't Load unless clicked on day

### ISSUE THREAD

**Issue by McSaverInvestments** [yurkinh/Plugin.Maui.Calendar#19]
Not sure if this is an issue, more like don't know how to change the current version to this (image below)

When I start up the calendar i see two selectors and would like to change it one, with Month, Year as the header text.

Herte is my current code

    <cal:Calendar Events="{Binding Events}" 
                  EventsScrollViewVisible="True" 
                  VerticalOptions="Fill"
                    HorizontalOptions="Fill" 
                  ShowYearPicker="False" >

        <cal:Calendar.EventTemplate>
            <DataTemplate>
                <VerticalStackLayout>
                    <Label Text="{Binding Name}"></Label>
                    <Label Text="{Binding Description}"></Label>
                </VerticalStackLayout>
            </DataTemplate>
        </cal:Calendar.EventTemplate>

       
    </cal:Calendar>
 
![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/104718532/84797cf3-9356-404f-8e24-1046327359d4)

**Comment by Agistaris** [comment]
You can create a custom data template. Either use the built in header template and set a data template that way or hide the native header data template and create a create your own header with your desired functionality. Give me a basic idea of how you would like this to look and I'll give you a brief example of how this can done when I have time tomorrow. @McSaverInvestments

**Comment by McSaverInvestments** [comment]
Thank you, Agistaris.

**Comment by Agistaris** [comment]
@McSaverInvestments I kinda jimmy rigged this together from my code. This should cover most of the functionality that you desire and handle some unexpected behaviors from the calendar you might not be aware of, and handle scrolling, etc... **Make sure you use images for 'next_arrow.png' and 'prev_arrow.png'**. Make sure those images are set as **'MauiImage' in the properties** on the right hand side in visual studio. 

This example removes the header and footer of the calendar, if you like the footer, just set 'FooterSectionVisible' to 'True'. I chose not to use the Calendar header only because I didn't want to overwhelm you with data templates and references, if you wish to use the default calendar header with your own 'DataTemplate', you will need to reference the parent page as a binding source for bindings outside of the calendar itself. Otherwise, this effectively does the same thing...

**xaml:**
```
<Grid VerticalOptions="Start" x:Name="Calendar">

    <VerticalStackLayout >
        <Grid ColumnDefinitions="40,*,40" Margin="0" RowDefinitions="40" BackgroundColor ="White">
            <ImageButton Clicked="PreviousDate" Grid.Column="0" Source="back_arrow.png" WidthRequest="37.5" HeightRequest="37.5" HorizontalOptions="Center" VerticalOptions="Center"/>
            <ImageButton Clicked="NextDate" Grid.Column="2" Source="next_arrow.png" WidthRequest="37.5" HeightRequest="37.5" HorizontalOptions="Center" VerticalOptions="Center"/>
            <Label Grid.Column="1" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" FontAttributes="None" FontSize="20" TextColor="Black" Text="{Binding SelectedMonth}"/>
            
        </Grid>

        <cal:Calendar
            BackgroundColor="White"
            VerticalOptions="Start"
            x:Name="Cal"
            HeightRequest="335"
            FooterSectionVisible="False"
            HeaderSectionVisible="False">
        </cal:Calendar>
    </VerticalStackLayout>
</Grid>
```

C# (Code Behind):
```

public YourPage() 
{
    InitializeComponent();
    BindingContext = this;
    CalendarDate = DateTime.Now;
    Cal.SelectedDate = DateTime.Now.Date;
    Cal.DayTappedCommand = new Command(CalendarDayTapped);
    Cal.SwipeLeftCommand = new Command(CalendarSwipeLeft);
    Cal.SwipeRightCommand = new Command(CalendarSwipeRight);
}

private DateTime? _calendarDate = DateTime.Now.Date;
public DateTime? CalendarDate
{
    get => _calendarDate;
    set
    {
        _calendarDate = value;
        OnPropertyChanged(nameof(CalendarDate));
        SelectedMonth = CalendarDate?.ToString("MMMM, yyyy");
    }
}


private string _selectedMonth = "";
public string SelectedMonth
{
    get => _selectedMonth;
    set
    {
        _selectedMonth = value;
        OnPropertyChanged(nameof(SelectedMonth));
    }
}

private void CalendarDayTapped()
{
    var tempSelectedDate = Cal.SelectedDate;

    if (tempSelectedDate == null)
    {
        Cal.SelectedDate = CalendarDate;
    }
    else
    {
        CalendarDate = tempSelectedDate;
        if (CalendarDate?.Date < DateTime.Now.Date)
        {
            Cal.SelectedDayBackgroundColor = DarkTheme.Element_Warning;
        }
        else
        {
            Cal.SelectedDayBackgroundColor = DarkTheme.Carbs;
        }
    }

    if (CalendarDate != null)
    {
        App.SelectedDate = (DateTime)CalendarDate;
        GetPage.Dashboard().RefreshData(false);
    }
}

private void CalendarPreviousDate(object sender, EventArgs e)
{
    CalendarDate = CalendarDate?.AddMonths(-1);
    Cal.PrevLayoutUnitCommand.Execute(this);
}

private void CalendarSwipeLeft()
{
    CalendarDate = CalendarDate?.AddMonths(1);
    Cal.NextLayoutUnitCommand.Execute(this);
}

private void CalendarNextDate(object sender, EventArgs e)
{
    CalendarDate = CalendarDate?.AddMonths(1);
    Cal.NextLayoutUnitCommand.Execute(this);
}

private void CalendarSwipeRight()
{
    CalendarDate = CalendarDate?.AddMonths(-1);
    Cal.PrevLayoutUnitCommand.Execute(this);
}
```

**Comment by McSaverInvestments** [comment]
Thank you, I will give it a try.

**Comment by McSaverInvestments** [comment]
Hey Agistaris,

I have made some changes to what you supplied, the issue I'm having now is with Events.

What I'm seeing is every time I select a new month I reload the events and the calendar is no displaying the, unless I select the day with an event I then see the dot.

xaml:

<Grid VerticalOptions="Fill">
    <VerticalStackLayout >
        <Grid ColumnDefinitions="*,*,*" Margin="0" RowDefinitions="90" BackgroundColor ="White">
            <ImageButton Clicked="CalendarPreviousDate" Grid.Column="0" Source="../Assets/prev_arrow.png" WidthRequest="37.5" HeightRequest="37.5" HorizontalOptions="Center" VerticalOptions="Center"/>
            <Label Grid.Column="1" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" VerticalTextAlignment="Center" HorizontalTextAlignment="Center" FontAttributes="None" FontSize="20" TextColor="Black" Text="{Binding SelectedMonth}"/>
            <ImageButton Clicked="CalendarNextDate" Grid.Column="2" Source="../Assets/next_arrow.png" WidthRequest="37.5" HeightRequest="37.5" HorizontalOptions="Center" VerticalOptions="Center"/>
        </Grid>
        <cal:Calendar
            x:Name="Cal"
            Events="{Binding Events}"
            BackgroundColor="White"
            VerticalOptions="Start"
            FooterSectionVisible="True"
            HeaderSectionVisible="False"
            EventsScrollViewVisible="False"
            SelectedDayBackgroundColor="Blue"
            EventIndicatorColor="Green"
            EventIndicatorSelectedColor="Blue"
            EventIndicatorSelectedTextColor="Black"
            EventIndicatorType="Background">
        </cal:Calendar>
        <ListView ItemsSource="{Binding SelectedDateEvents}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout>
                            <Label Text="{Binding Description}" />
                            <Label Text="{Binding Name}" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </VerticalStackLayout>
</Grid>



C# xaml:



  private EventCollection _events = new EventCollection();
  public EventCollection Events
  {
      get => _events;
      set
      {
          _events = value;
          OnPropertyChanged(nameof(_events));
      }
  }



  private List<EventModel> _SelectedDateEvents = new List<EventModel>();
  public List<EventModel> SelectedDateEvents
  {
      get => _SelectedDateEvents;
      set
      {
          _SelectedDateEvents = value;
          OnPropertyChanged(nameof(SelectedDateEvents));
      }
  }


  private DateTime? _calendarDate = DateTime.Now.Date;
  public DateTime? CalendarDate
  {
      get => _calendarDate;
      set
      {
          _calendarDate = value;
          OnPropertyChanged(nameof(CalendarDate));
          Cal.SelectedDate = value;
          SelectedMonth = CalendarDate?.ToString("MMMM, yyyy");
      }
  }

 private string _selectedMonth = "";
 public string SelectedMonth
 {
     get => _selectedMonth;
     set
     {
         _selectedMonth = value;
         OnPropertyChanged(nameof(SelectedMonth));
     }
 }

  public CalendarPage()
  {
      InitializeComponent();

      BindingContext = this;

      Events = CreateEvents(DateTime.Now.Date);

      CalendarDate = DateTime.Now.Date;

      Cal.DayTappedCommand = new Command(CalendarDayTapped);

      Cal.SwipeLeftCommand = new Command(CalendarSwipeLeft);

      Cal.SwipeRightCommand = new Command(CalendarSwipeRight);
  }


   private void CalendarPreviousDate(object sender, EventArgs e)
   {
       Cal.Events.Clear();
       Events.Clear();
       SelectedDateEvents = new List<EventModel>();
       CalendarDate = CalendarDate?.AddMonths(-1);
       Cal.Events = CreateEvents(CalendarDate.Value);
       Events = Cal.Events;
       Cal.PrevLayoutUnitCommand.Execute(this);
       CalendarDayTapped();
   }

   private void CalendarSwipeLeft()
   {
       Cal.Events.Clear();
       Events.Clear();
       SelectedDateEvents = new List<EventModel>();
       CalendarDate = CalendarDate?.AddMonths(1);
       Cal.Events = CreateEvents(CalendarDate.Value);
       Events = Cal.Events;
       Cal.NextLayoutUnitCommand.Execute(this);
       CalendarDayTapped();
   }

   private void CalendarNextDate(object sender, EventArgs e)
   {
       Cal.Events.Clear();
       Events.Clear();
       SelectedDateEvents = new List<EventModel>();
       CalendarDate = CalendarDate?.AddMonths(1);
       Cal.Events = CreateEvents(CalendarDate.Value);
       Events = Cal.Events;
       Cal.NextLayoutUnitCommand.Execute(this);
       CalendarDayTapped();
   }

   private void CalendarSwipeRight()
   {
       Cal.Events.Clear();
       Events.Clear();
       SelectedDateEvents = new List<EventModel>();
       CalendarDate = CalendarDate?.AddMonths(-1);
       Cal.Events = CreateEvents(CalendarDate.Value);
       Events = Cal.Events;
       Cal.PrevLayoutUnitCommand.Execute(this);
       CalendarDayTapped();
   }

   private void CalendarDayTapped()
   {
       var tempSelectedDate = Cal.SelectedDate;

       if (tempSelectedDate != null)
       {
           if (Events.TryGetValue(tempSelectedDate.Value, out System.Collections.ICollection eventsForDate))
           {
               SelectedDateEvents = (List<EventModel>)Events[tempSelectedDate.Value];
           }
           else
           {
               SelectedDateEvents = null;
           }

           CalendarDate = tempSelectedDate;
           Cal.Events = Events;
       }
   }




public class EventModel
{
    public string Name { get; set; }
    public string Description { get; set; }
}

  public EventCollection CreateEvents(DateTime aDate)
  {


// you can change this section to support
// Events = new EventCollection
// {
//     [DateTime.Now] = new List<EventModel>
//     {
//         new EventModel { Name = "Cool event1", Description = "This is Cool event1's description!" },
//         new EventModel { Name = "Cool event2", Description = "This is Cool event2's description!" }
//     },
//     // 5 days from today
//     [DateTime.Now.AddDays(5)] = new List<EventModel>
//     {
//         new EventModel { Name = "Cool event3", Description = "This is Cool event3's description!" },
//         new EventModel { Name = "Cool event4", Description = "This is Cool event4's description!" }
//     },
//     // 3 days ago
//     [DateTime.Now.AddDays(-3)] = new List<EventModel>
//     {
//         new EventModel { Name = "Cool event5", Description = "This is Cool event5's description!" }
//     },
//     // custom date
//     [new DateTime(2020, 3, 16))] = new List<EventModel>
//     {
//         new EventModel { Name = "Cool event6", Description = "This is Cool event6's description!" }
//     }
// };
      var cleanDate = new DateTime(aDate.Year, aDate.Month, 1, 12, 0, 0);

      var newEvents = new EventCollection();

      var DaysInfo = ServiceCalls.GetCalendar(cleanDate);

      if (DaysInfo.Any())
      {
          foreach (TradingCalendar eventModel in DaysInfo)
          {
              var existingEvents = new List<EventModel>();

              var item = new EventModel()
              {
                  Name = eventModel.AccountName,
                  Description = eventModel.NetAmount.ToString()
              };

              existingEvents.Add(item);

              newEvents.Add(eventModel.Date, existingEvents);
          }

          Events = newEvents;
          Cal.Events = Events;
      }
      else
      {
          Events = new EventCollection();
      }

      return Events;
  }

**Comment by McSaverInvestments** [comment]
@Agistaris
