### ISSUE TITLE
No events in the EventTemplate in the samples

### ISSUE THREAD

**Issue by vallgrenerik** [yurkinh/Plugin.Maui.Calendar#2]
Hi! 

Thank you for the port, looks good.
But i can't seem to figure out why the EventTemplate is not showing any data.
I have tried your sample and it only looks like this; 
It doesn't show any data at all.

![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/26163937/c522eaca-24fb-4f9e-abab-40bcbc0bb957)

My own app, that worked with the 'original' plugin does the same. 
Do you have any suggestions? 

Thank you! 💯

**Comment by yurkinh** [comment]
Hi @vallgrenerik 
Thanks for the feedback.
Try to set `EventsScrollViewVisible = true`
