### ISSUE TITLE
Selected date not marked on calendar

### ISSUE THREAD

**Issue by TomaszZakrzewski** [yurkinh/Plugin.Maui.Calendar#30]
Hello.
 
I have a problem with my simple implementation of the calendar.
I am binding a date to the SelectedDate property and i get the selected date in the footer section but the selected date is not marked on the calendar itself.
The selection on the calendar only happens when i click on a date.
I also tried to bind the property ShownDate to my date property but with no result.

![Screenshot_1707420405](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/62554233/56f18b55-2974-456a-9117-46b694acf7bc)

**Comment by yurkinh** [comment]
Hi @TomaszZakrzewski 
Thanks for reporting an issue. Looks like a problem with binding.
I will take a look at it

**Comment by yurkinh** [comment]
@TomaszZakrzewski  As a temporary workaround I can suggest you to force Two Way binding mode
`SelectedDate={Binding SelectedDate, Mode=TwoWay}`
I was able to reproduce this issue and will check how to fix it

**Comment by TomaszZakrzewski** [comment]
Thank you @yurkinh 

I will test this solutions and get back to you.

**Comment by yurkinh** [comment]
Hi @TomaszZakrzewski 
Check please the latest v1.1.2 nuget version. It contains fix for the mentioned issue
