### ISSUE TITLE
Disable collapse of the calender if date is clicked

### ISSUE THREAD

**Issue by ablersch** [yurkinh/Plugin.Maui.Calendar#34]
Hi,

is it possible to deactivate the collapse when clicking on the date of a selected event, so that the calendar is not collapsed.

Regards
Andreas

**Comment by yurkinh** [comment]
Hi @ablersch 
Yes. Check please AdvancedCalendar page and inside calendar footer remove
"
 
            <TapGestureRecognizer Command="{Binding ShowHideCalendarCommand}" />
        
"
You have full control over footer and header of calendar

**Comment by ablersch** [comment]
Thx, works with a custom footer section.
