### ISSUE TITLE
Empty template not showing

### ISSUE THREAD

**Issue by ablersch** [yurkinh/Plugin.Maui.Calendar#35]
Hi,

I added an empty template but it never appears in my app. Is any other configuration necessary? I tried in windows and android emulator.
In the advanced calendar example the empty template also do not appear.

`
<controls:Calendar.EmptyTemplate>
<DataTemplate>
        <Label Grid.Column="0" FontAttributes="Bold" FontSize="Medium" Text="Test"
            TextColor="{StaticResource Primary}" VerticalOptions="Center" VerticalTextAlignment="Center" />
    </DataTemplate>
</controls:Calendar.EmptyTemplate>
`

**Comment by yurkinh** [comment]
Hi @ablersch 
Can you provide some sample?

**Comment by yurkinh** [comment]
Hi @ablersch 
Check please the latest version v1.1.4 from nuggets -it contains fis for missing EmptyViewTemplate from pull #38

**Comment by ablersch** [comment]
THX for fast fixing, it works now.
