### ISSUE TITLE
Microsoft.Maui.Controls.Xaml.XamlParseException: 'Position 26:16. Can not find the object referenced by `calendar`

### ISSUE THREAD

**Issue by jasonnator** [yurkinh/Plugin.Maui.Calendar#4]
![image](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/1467811/084db44c-3395-4392-8726-8f914bbc306d)

I'm using a MultiSelectionCalendar and need the application to load it's hosting page right away. When doing this, there are exceptions which get thrown due to the BindingContext="{x:Reference calendar}" field/property not yet being fully initialized.

[https://github.com/yurkinh/Plugin.Maui.Calendar/blob/ae774fe0f025de8ae8e8307c8dcde51e6867d8a0/src/Plugin.Maui.Calendar/Shared/Controls/Calendar.xaml#L59](url)

It's the footer template which is throwing the exception(s) which I have verified by commenting the entire template out. With the template removed, the application does not crash and the page loads fine but requires a fix, see below:

In [https://github.com/yurkinh/Plugin.Maui.Calendar/blob/ae774fe0f025de8ae8e8307c8dcde51e6867d8a0/src/Plugin.Maui.Calendar/Shared/Controls/MonthDaysView.cs#L596](url)
I have edited the method as follows:

``` csharp
internal void UpdateAndAnimateDays(bool animate)
{
    if (Culture == null)
        return;

    if (BindingContext == null)
    {
        UpdateDays();
        _lastAnimationTime = DateTime.UtcNow;
    }
    else
    {
        Animate(() => _daysControl.FadeTo(animate ? 0 : 1, 50),
                () => _daysControl.FadeTo(1, 200),
                () => UpdateDays(),
                _lastAnimationTime = DateTime.UtcNow,
                () => UpdateAndAnimateDays(false));//send false to prevent flashing if several property bindings are changed
    }
}
```

I wanted to discuss this some before submitting a PR since commenting the template means that this is likely a cascading issue which may cause some widespread changes.

**Comment by jasonnator** [comment]
The fix introduced to UpdateAndAnimateDays was because of a IAnimationManager not found exception probably because the control hadn't finished loading.

**Comment by yurkinh** [comment]
Hi @jasonnator 
Recently I have encountered the same issue ""Unable to find IAnimationManager for 'Microsoft.Maui.Controls.Grid'. (Parameter 'animatable')"
Have you done already some investigation on this?

**Comment by yurkinh** [comment]
There is some similar topic in .NET maui repo https://github.com/dotnet/maui/pull/6364

**Comment by yurkinh** [comment]
@jasonnator I have pushed fix and published updated nuget
