### ISSUE TITLE
[Enhancement] Allow background color to be set for Events scrollview as well as calendar itself

### ISSUE THREAD

**Issue by edgiardina** [yurkinh/Plugin.Maui.Calendar#43]
Right now I can set a calendar background color but that colors the entire events scrollview as well as the calendar. I want the calendar events scrollview to be a separate color than the calendar itself, which is how the native app Calendar appears in iOS.

**Comment by yurkinh** [comment]
Hi @edgiardina 
Thanks for the suggestion. I think it won't be difficult to add hence I will try to implement this with next minor plugin update

**Comment by usefulBeeing** [comment]
I think you can accomplish the same goal by setting the Background Color of the [Events DataTemplate StackLayout](https://github.com/yurkinh/Plugin.Maui.Calendar?tab=readme-ov-file#binding-events).

**Comment by edgiardina** [comment]
@usefulBeeing unfortunately not, if you set the background color of the stacklayout there's still spacing and padding between the items drawn that won't have the background color. Whatever container the DataTemplate populates needs the background color which we can't pass to the datatemplate itself.

**Comment by usefulBeeing** [comment]
@edgiardina , I didn't notice any spacing when I copied and pasted the [READEME sample](https://github.com/yurkinh/Plugin.Maui.Calendar?tab=readme-ov-file#binding-events). 

Here's what it looks like on my side:

<img width="395" alt="CalBack" src="https://github.com/user-attachments/assets/b7a69936-a612-4033-9932-ac51166c5dc0">


Even if there were to be spacing, you still could wrap the StackPanel in a Grid as a workaround, and set the BackgroundColor of the Grid.

With that said, I think the feature you're asking for is awesome and should be implemented.
