### ISSUE TITLE
Eventindicators not rendered when adding new events

### ISSUE THREAD

**Issue by marcustindab** [yurkinh/Plugin.Maui.Calendar#52]
Hi,

We're having some issues where new events are added to the Calendar. The indicator "dots" aren't being drawned before we have clicked on a day we know have an event. Then the dots for all events are being displayed/rendered in calendar. 
How to solve this? Trigger any OnPropertyChanged from our viewmodel?

**Comment by marcustindab** [comment]
This issue exists in both version 1.1.4 and 1.1.5.

Take a look at this video recording:
https://github.com/yurkinh/Plugin.Maui.Calendar/assets/147273496/a1808210-e918-411d-aa10-1a139b01884c

**Comment by yurkinh** [comment]
Hi @marcustindab 
Thanks for the report and video.
Could you provide some sample for easier debugging?

**Comment by marcustindab** [comment]
Hi @yurkinh ,

I've created a small reproduction of this. See the attached zip-file.
[Sandbox.zip](https://github.com/yurkinh/Plugin.Maui.Calendar/files/15011393/Sandbox.zip)

**Comment by yurkinh** [comment]
Hi @marcustindab 
I will take a look later today. Thanks for the repro sample

**Comment by yurkinh** [comment]
@marcustindab 
Replacing TryAdd with Add has fixed this issue)
Events.Add(new DateTime(date.Year, Month, day), new List<EventItem> { new() { Description = "An Event" } });

**Comment by marcustindab** [comment]
Thank you for your quick repsonse - your suggested change solved the issue for us. 
Keep up the good work!

Closing the issue.
