### ISSUE TITLE
Calendar Day values disappear when changing CalendarLayout at runtime

### ISSUE THREAD

**Issue by InquisitorJax** [yurkinh/Plugin.Maui.Calendar#54]
See here - changing the viewmodel.CalendarLayout when buttons tapped (Android)

![calendar](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/1822976/d93b1003-fdd5-42a5-b8f7-7ff7ac638f66)

**Comment by yurkinh** [comment]
Hi @InquisitorJax 
Check please latest v1.1.6

**Comment by InquisitorJax** [comment]
fixed :)
