### ISSUE TITLE
Certain months are being cropped

### ISSUE THREAD

**Issue by inimirpaz** [yurkinh/Plugin.Maui.Calendar#57]
I.e. June 2024

![immagine](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/56956625/dfd2a020-27b5-42f9-b0c8-15b250eb4179)

This happens also in other CalendarLayouts. The Xamarin plugin added an extra row (upcoming month) at the end to prevent this behavior I guess.

**Comment by inimirpaz** [comment]
Hi @yurkinh 
I tried playing with it (even though in the real project I am migrating to .NET MAUI I pre-processed all of my xamls to have the spacing explicitly set to 6 whenever it was not specified otherwise) but I cannot get it to display the last row. I tried to use stacklayouts, vertical, grid, nothing at all (root content of the page) and to play with the hor/ver options but nothing seems to work. Am I missing something?

Repro: https://github.com/inimirpaz/maui_issues/tree/calendar_event_issue

**Comment by ross8alex** [comment]
Seems to be whenever there's a 6th row it doesn't automatically expand to show that extra row.

**Comment by yurkinh** [comment]
Hi @inimirpaz @ross8alex 
Can you try this custom nuget build with fix locally?
[Plugin.Maui.Calendar.1.1.8.nupkg.zip](https://github.com/user-attachments/files/15538741/Plugin.Maui.Calendar.1.1.8.nupkg.zip)

**Comment by inimirpaz** [comment]
Hi @yurkinh , it works as expected, thanks!

Just a side note: I launched the repro project but since the "current date" is already June the issue was not there anymore, even with the current latest stable release, the last row is shown. I had to change the current date to, say, May to have it back and test the custom nuget. Anyway, this is kind of expected.

**Comment by yurkinh** [comment]
Fix published with nuget version 1.1.8
