### ISSUE TITLE
Events are not being displayed in the detail panel

### ISSUE THREAD

**Issue by inimirpaz** [yurkinh/Plugin.Maui.Calendar#58]
Repro: https://github.com/inimirpaz/maui_issues/tree/calendar_event_issue
(was not the case with the Xamarin plugin)

The dot appears in the days containg events but the Calendar.EventTemplate are not being shown in the detail panel.
![immagine](https://github.com/yurkinh/Plugin.Maui.Calendar/assets/56956625/a4a16548-b5ee-4fe6-b23a-faee50b77437)

**Comment by yurkinh** [comment]
Hi @inimirpaz 
Thanks for the repro sample. 
I will take a look at this issue

**Comment by inimirpaz** [comment]
Hi @yurkinh 
Thanks, that was it! May I suggest to add that to the repo readme? (It is a change of a previous default behavior)
