### ISSUE TITLE
[Enhancement] Change text color for Selected Other Month days

### ISSUE THREAD

**Issue by ross8alex** [yurkinh/Plugin.Maui.Calendar#60]
Currently you can change the text color for Other Month days, and you can change the text color for selected days, but not the Selected Other Month Days.

Love this project btw, keep up the great work! :)

**Comment by yurkinh** [comment]
Hi @gvhung 
This PR will break existing functionality. 
Calendar has specific property "WeekendDayColor" to change Wekkend days color. No need to remove this functionality from calendar

**Comment by yurkinh** [comment]
Hi @ross8alex 
Thanks for the kind words. 
Yes currently we have "OtherMonthDayColor" only. There is one annoying bug in the pipeline with cutted days and after this I will take a look to this separate OtherMonthSelectedDay property
