### ISSUE TITLE
Question: Is it possible to alter the EventIndicators based on the calendar event?

### ISSUE THREAD

**Issue by marcustindab** [yurkinh/Plugin.Maui.Calendar#64]
Hi!

We're still enjoying your great plugin. 

Is it possible to have different Event indicator colors, depending on the calendar event type? E.g. if you have scheduled a meeting, we might want to have a red indicator dot, but if your free, we want a green dot.

Is this possible in the current version of the plugin?

Thanks!

**Comment by yurkinh** [comment]
Hi @marcustindab 
Have you checked the AdvacncedPage Calendar?
I'm not sure whether this functionality is enough but there is a sample how to setup EventIndicator color from code

**Comment by marcustindab** [comment]
Works wonders! Thanks a lot!
