### ISSUE TITLE
PrevMonthCommand, NextMonthCommand is removed

### ISSUE THREAD

**Issue by yashaswinidc** [yurkinh/Plugin.Maui.Calendar#68]
PrevMonthCommand, NextMonthCommand These 2 commands to switch between the Months is removed. Which was available in "Xamarin.Plugin.Calendar" earlier.

Any alternative solution to achieve this would be helpful

<img width="491" alt="image" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/148186518/22637c42-9c53-471d-9f0e-3f0578f2ca61">
<img width="452" alt="image" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/148186518/ab79ef29-0df3-4034-a336-b7d9b2972493">

**Comment by yashaswinidc** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<ContentView
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:ctrlcal="clr-namespace:Plugin.Maui.Calendar.Controls;assembly=Plugin.Maui.Calendar">
    <ContentView.Content>
          <ctrlcal:Calendar x:Name="monthView"
                            Margin="0,0,0,0"
                            Padding="10,10,10,20"
                            Grid.Row="0"
                            IsVisible="{Binding CanCalenderVisible}"
                            AnimateCalendar="True"
                            BackgroundColor="White"
                            DayTappedCommand="{Binding DayTappedCommand}"
                            DayViewCornerRadius="20"
                            DayViewSize="40"
                            DaysLabelStyle="{StaticResource daysLabelStyle}"
                            DaysTitleColor="#2b3990"
                            DaysTitleHeight="40"
                            DaysTitleLabelStyle="{StaticResource daysTitleLabelStyle}"
                            DaysTitleMaximumLength="TwoChars"
                            MaximumDate="{Binding MaxDate}"
                            MinimumDate="{Binding MinDate}"
                            DeselectedDayTextColor="#485f5c"
                            DisableSwipeDetection="True"
                            EventIndicatorColor="Red"
                            EventIndicatorSelectedColor="IndianRed"
                            EventIndicatorSelectedTextColor="AliceBlue"
                            EventIndicatorTextColor="#485f5c"
                            EventIndicatorType="BottomDot"
                            Events="{Binding Events}"
                            HorizontalOptions="FillAndExpand"
                            MonthLabelColor="Red"
                            Month="{Binding MonthYear}"
                            Year="{Binding MonthYear}"
                            OtherMonthDayColor="#f2efef"
                            OtherMonthDayIsVisible="True"
                            SelectedDate="{Binding SelectedDate}"
                            SelectedDateColor="Violet"
                            SelectedDateTextFormat="ddd, dd MMM yyyy"
                            SelectedDayBackgroundColor="#ee2d25"
                            SelectedDayTextColor="White"
                            SwipeToChangeMonthEnabled="False"
                            SwipeUpToHideEnabled="False"
                            TodayFillColor="Transparent"
                            TodayOutlineColor="#ee2d25"
                            VerticalOptions="Start"
                            HeightRequest="380"
                            YearLabelColor="Blue">
            <ctrlcal:Calendar.HeaderSectionTemplate>
              <local:CalendarHeader />
            </ctrlcal:Calendar.HeaderSectionTemplate>
            <ctrlcal:Calendar.FooterSectionTemplate>
              <DataTemplate>
                <local:CalendarFooter />
              </DataTemplate>
            </ctrlcal:Calendar.FooterSectionTemplate>
          </ctrlcal:Calendar>
          <BoxView BackgroundColor="{Binding ArrowBgClr}"
                   Grid.Row="1"
                   HeightRequest="11" />
          <ui:Image Grid.Row="1"
                    Margin="0,5,0,0"
                    VerticalOptions="CenterAndExpand"
                    HorizontalOptions="FillAndExpand"
                    EdgeInsets="0,1,0,1"
                    ResizeMode="Stretch"
                    Rotation="180"
                    IsVisible="{Binding CanCalenderVisible}"
                    Source="navbar_shadow" />
          <BoxView BackgroundColor="#e1e3ea"
                   Grid.Row="1"
                    Margin="0,0,0,-15"
                    VerticalOptions="Center"
                    HorizontalOptions="Center"
                   CornerRadius="17"
                   WidthRequest="100"
                   HeightRequest="35" />
        </Grid>
    </ContentView.Content>
</ContentView>


<?xml version="1.0" encoding="UTF-8"?>
<DataTemplate
  xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
  <Grid Margin="0,2"
        Padding="0"
        HorizontalOptions="FillAndExpand"
        IsVisible="{Binding ShowMonthPicker}"
        VerticalOptions="Start">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="1*" />
      <ColumnDefinition Width="3*" />
      <ColumnDefinition Width="1*" />
    </Grid.ColumnDefinitions>
    <ImageButton  HorizontalOptions="Start"
               Grid.Column="0" Margin="5,0,0,0"
               WidthRequest="27"
               HeightRequest="27"
               Command="{Binding PrevMonthCommand}"
               Source="calenderleftnormal"
               VerticalOptions="Center"/>
    <Label Grid.Column="1"
           FontAttributes="Bold"
           FontSize="Medium"
           WidthRequest="100"
           HorizontalOptions="Center"
           VerticalOptions="Center"
           TextColor="#2b3990"
           LineBreakMode="NoWrap">
           <Label.FormattedText>
               <FormattedString>
                   <Span Text="{Binding Month, Converter={StaticResource MonthToText}, Mode=TwoWay}" />
                   <Span Text=" " />
                   <Span Text="{Binding Year, Mode=TwoWay}" />
               </FormattedString>
           </Label.FormattedText>
    </Label>
    <ImageButton HorizontalOptions="End"
               Grid.Column="2" Margin="0,0,5,0"
               WidthRequest="27"
               HeightRequest="27"
               Command="{Binding NextMonthCommand}"
               Source="calenderrightnormal"
               VerticalOptions="Center" />
  </Grid>
</DataTemplate>



<?xml version="1.0" encoding="UTF-8"?>
<ContentView
  xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
  <Grid HeightRequest="0"
        HorizontalOptions="FillAndExpand"
        VerticalOptions="FillAndExpand">
  </Grid>
</ContentView>


This is the minimal solution to Check the issue.

**Comment by yashaswinidc** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<DataTemplate
  xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
  <Grid Margin="0,2"
        Padding="0"
        HorizontalOptions="FillAndExpand"
        IsVisible="{Binding ShowMonthPicker}"
        VerticalOptions="Start">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="1*" />
      <ColumnDefinition Width="3*" />
      <ColumnDefinition Width="1*" />
    </Grid.ColumnDefinitions>
    <ImageButton  HorizontalOptions="Start"
               Grid.Column="0" Margin="5,0,0,0"
               WidthRequest="27"
               HeightRequest="27"
               Command="{Binding PrevMonthCommand}"
               Source="calenderleftnormal"
               VerticalOptions="Center"/>
    <Label Grid.Column="1"
           FontAttributes="Bold"
           FontSize="Medium"
           WidthRequest="100"
           HorizontalOptions="Center"
           VerticalOptions="Center"
           TextColor="#2b3990"
           LineBreakMode="NoWrap">
           <Label.FormattedText>
               <FormattedString>
                   <Span Text="{Binding Month, Converter={StaticResource MonthToText}, Mode=TwoWay}" />
                   <Span Text=" " />
                   <Span Text="{Binding Year, Mode=TwoWay}" />
               </FormattedString>
           </Label.FormattedText>
    </Label>
    <ImageButton HorizontalOptions="End"
               Grid.Column="2" Margin="0,0,5,0"
               WidthRequest="27"
               HeightRequest="27"
               Command="{Binding NextMonthCommand}"
               Source="calenderrightnormal"
               VerticalOptions="Center" />
  </Grid>
</DataTemplate>

**Comment by yurkinh** [comment]
Hi @yashaswinidc 
Those commands should be present. Check please Advanced sample "CalendarHeader" control

**Comment by yashaswinidc** [comment]
Hi @yurkinh, Thanks for the response

PrevLayoutUnitCommand & NextLayoutUnitCommand are the replaced commands.
