### ISSUE TITLE
Calendar items are not loading, App crash issue

### ISSUE THREAD

**Issue by yashaswinidc** [yurkinh/Plugin.Maui.Calendar#72]
<img width="325" alt="image" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/148186518/271fa468-09b0-4933-ba01-6aa077aeba8f">
<img width="324" alt="image" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/148186518/359ad21c-de45-431f-bbdf-d448574c1966">
<img width="355" alt="image" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/148186518/a6a85591-c11b-447f-8a81-9b260505260c">

I'm encountering an issue with a Calendar component where it initially displays the same way on both Android and iOS, similar to Image 1. However, when I navigate to other pages and return, it changes to the appearance shown in Images 2 (iOS) and 3(Android). Additionally, the app crashes. This issue occurs consistently just by initializing the month view of the Calendar component from the package.

**Comment by yurkinh** [comment]
Hi @yashaswinidc 
As a workaround, you can downgrade to the version 1.1.6
I plan to release new version today or tomorrow with fixes

**Comment by yashaswinidc** [comment]
Hello @yurkinh, I attempted using version 1.1.6, but I'm still experiencing the same issue. Thanks for your response, and I look forward to the upcoming release.

**Comment by yurkinh** [comment]
Hi @yashaswinidc 
Check please v 1.1.9

**Comment by yashaswinidc** [comment]
Hi @yurkinh , I tried implementing this version, but it requires Microsoft.Maui.Controls version 8.0.60 or higher. Unfortunately, it automatically downgrades to Microsoft.Maui.Controls 8.0.40, which prevents my app from running properly.

**Comment by yurkinh** [comment]
@yashaswinidc  Can you temporarily upgrade your app to 8.0.60 to test the fix?
I have updated calendar to the latest maui version cause it contains a lot of fixes. But I will think about downgrading it to 8.0.40 cause a lot of developers stay on 8.0.40

**Comment by yashaswinidc** [comment]
@yurkinh I did it and still the issue persists.

**Comment by yurkinh** [comment]
@yashaswinidc Can you provide some minimal repro sample?
Try to call the Dispose() method when leaving the page.

**Comment by yashaswinidc** [comment]
<ctrlcal:Calendar x:Name="monthView"
                  Margin="0,0,0,0"
                  Padding="10,10,10,20"
                  Grid.Row="0"
                  IsVisible="{Binding CanCalenderVisible}"
                  AnimateCalendar="True"
                  BackgroundColor="White"
                  DayTappedCommand="{Binding DayTappedCommand}"
                  DayViewCornerRadius="20"
                  DayViewSize="40"
                  DaysLabelStyle="{StaticResource daysLabelStyle}"
                  DaysTitleColor="#2b3990"
                  DaysTitleHeight="40"
                  DaysTitleLabelStyle="{StaticResource daysTitleLabelStyle}"
                  DaysTitleMaximumLength="TwoChars"
                  MaximumDate="{Binding MaxDate}"
                  MinimumDate="{Binding MinDate}"
                  DeselectedDayTextColor="#485f5c"
                  DisableSwipeDetection="True"
                  EventIndicatorColor="Red"
                  EventIndicatorSelectedColor="IndianRed"
                  EventIndicatorSelectedTextColor="AliceBlue"
                  EventIndicatorTextColor="#485f5c"
                  EventIndicatorType="BottomDot"
                  Events="{Binding Events}"
                  HorizontalOptions="FillAndExpand"
                  MonthLabelColor="Red"
                  Month="{Binding MonthYear}"
                  Year="{Binding MonthYear}"
                  OtherMonthDayColor="#f2efef"
                  OtherMonthDayIsVisible="True"
                  SelectedDate="{Binding SelectedDate}"
                  SelectedDateColor="Violet"
                  SelectedDateTextFormat="ddd, dd MMM yyyy"
                  SelectedDayBackgroundColor="#ee2d25"
                  SelectedDayTextColor="White"
                  SwipeToChangeMonthEnabled="False"
                  SwipeUpToHideEnabled="False"
                  TodayFillColor="Transparent"
                  TodayOutlineColor="#ee2d25"
                  VerticalOptions="Start"
                  HeightRequest="380"
                  YearLabelColor="Blue">
    <ctrlcal:Calendar.HeaderSectionTemplate>
        <local:CalendarHeader />
    </ctrlcal:Calendar.HeaderSectionTemplate>
    <ctrlcal:Calendar.FooterSectionTemplate>
        <DataTemplate>
            <local:CalendarFooter />
        </DataTemplate>
    </ctrlcal:Calendar.FooterSectionTemplate>
</ctrlcal:Calendar>

In my viewmodel SelectedDate is defined this way
public DateTime SelectedDate { get; set; } = DateTime.Now.Date;

However, when I attempt to update the SelectedDate in the DayTappedCommand, the app crashes. The issue persists even without the custom header and footer elements. The calendar control is used as follows in another page:
<local:CustomCalenderView x:Name="CustomCalender" Grid.Row="1"/>

**Comment by yurkinh** [comment]
@yashaswinidc  Could you provide logs or a full repro sample to trace the issue?

**Comment by yashaswinidc** [comment]
Hi @yurkinh, The issue has been resolved. I didn't do any fix from my side. 
Currently I'm using latest version of the package. Thanks for the support.
