### ISSUE TITLE
Setting OtherMonthDayIsVisible to False is not working

### ISSUE THREAD

**Issue by usefulBeeing** [yurkinh/Plugin.Maui.Calendar#77]
Setting OtherMonthDayIsVisible property to False refreshes the Calendar (**Update**: and disables the selection of those days) but does not hide the next or previous month days.

`        <controls:Calendar 
                           OtherMonthDayIsVisible="False"
                           OtherMonthDayColor="Red"
        />`

<img width="387" alt="OtherMonthDayIsVisibleFalseBug" src="https://github.com/yurkinh/Plugin.Maui.Calendar/assets/174826497/02fd1b93-9e88-40b0-a6a7-b9c0f9467765">

Great plugin by the way! Straightforward and easy to work with.

Thank you for sharing this with the community.

**Comment by yurkinh** [comment]
Hi @usefulBeeing 
Thanks for the feedback. I will take a look at this issue in the next few days

**Comment by usefulBeeing** [comment]
I found a workaround by setting `OtherMonthDayColor` to `Transparent`.

**Comment by yurkinh** [comment]
Great! Easy to use workaround until I will fix this issue
