### ISSUE TITLE
Raising ICommand and passing DateTime from the selected date after the user selects a date

### ISSUE THREAD

**Issue by SEGMK** [yurkinh/Plugin.Maui.Calendar#78]
Hi, I'm quite new to MAUI and DataBinding so if the answer to that is obvious I'm so sorry.

How can I Bind the ICommand method to the calendar such that after the user selects a date this binded method will be called and how can I pass the selected by user date as the argument to my ICommand method?

**Comment by usefulBeeing** [comment]
As described [here](https://github.com/yurkinh/Plugin.Maui.Calendar?tab=readme-ov-file#calendar-swipe-customizations), you could do something like this:

`<controls:Calendar DayTappedCommand="{Binding DoSomethingCommand}">`

In your ViewModel, you should inject a DateTime object into your Command or Method:

`DoSomething(DateTime dateTime)`
