### ISSUE TITLE
Is It possible to listen or trigger a command when the month and year change in the calendar?

### ISSUE THREAD

**Issue by Edwinroman30** [yurkinh/Plugin.Maui.Calendar#84]
Hi Yurkinh, thanks for making this great plugin available. I'm using .net 8 (MAUI) for android and would like to listen to any command when the _month_ or_year_ change in the calendar, with the purpose of fetching data from a web API. I was looking through the different sample, but I could not find something that fit my requirement. Any suggestion will be helpful.

Thanks you @yurkinh

**Comment by yurkinh** [comment]
Hi @Edwinroman30 
Have you checked AdvancedCalendar page?
`SwipeLeftCommand="{Binding PrevLayoutUnitCommand, Source={x:Reference MyCalendar}}"

  SwipeRightCommand="{Binding NextLayoutUnitCommand, Source={x:Reference MyCalendar}}"`

I think you can use "NextLayoutUnitCommand" to do an API call

**Comment by Edwinroman30** [comment]
Hi @yurkinh , I followed your recommendations and it worked to me. Thank you for responding to me and the guidelines.
