### ISSUE TITLE
Wrong day text color when deselected 

### ISSUE THREAD

**Issue by poochie89** [yurkinh/Plugin.Maui.Calendar#86]
When the selected date has an event and is selected, it does go black after deselection.
For days with no event this does not happen.

See the video below

https://github.com/user-attachments/assets/1e4ce45b-f141-4789-86b4-30b399eec740

**Comment by yurkinh** [comment]
Hi @poochie89 
Thanks for reporting an issue. I will take a look at this bug in the next few days

**Comment by MykhailoDav** [comment]
Hi @poochie89

I looked into your problem and found out that there is a small bug in the Calendar, I will think about how to solve it properly and make a pull request.

As a temporary solution, you can set the color of the **EventIndicatorTextColor** property to the same as **DeselectedDayTextColor** property!

**Comment by MykhailoDav** [comment]
Hi @poochie89,
Please let me know if my answer helped you!

**Comment by poochie89** [comment]
Yes workaround did the job
