### ISSUE TITLE
Bug where arrows are not visible in distribution (.aab)

### ISSUE THREAD

**Issue by gwise-vision** [yurkinh/Plugin.Maui.Calendar#87]
I applied the Font in the sample and it looks fine in debug, but when I distribute it as Release .aab, the arrows are broken.
Android Galaxy S20+

![image](https://github.com/user-attachments/assets/984da685-e728-4e79-92e6-e701060698eb)

**Comment by gwise-vision** [comment]
→
←

↑
↓
I solved it by replacing it with this character.

**Comment by yurkinh** [comment]
It looks like something is wrong with trimming or with the Samsung phone.
Could you try to run the app in release mode on the emulator or any other physical device to verify this?
