### ISSUE TITLE
How do I prevent deselecting a date?

### ISSUE THREAD

**Issue by clm-unifly** [yurkinh/Plugin.Maui.Calendar#88]
Hi,
In my app, I am in need to have a guaranteed selected date. If I tap on the already selected date it is deselected. Is there a way to prevent this?
Thanks,

**Comment by yurkinh** [comment]
Hi @clm-unifly 
There is "DayTappedCommand" which you can disable from the ViewModel after data is selected
```
[RelayCommand(CanExecute = Condition)]
Task EventSelected(object item)
{
}
```
