### ISSUE TITLE
Question: UI for list of events of the day

### ISSUE THREAD

**Issue by Rodionbar** [yurkinh/Plugin.Maui.Calendar#89]
Hello,

currently calendar marks days where we have events with a red dot, but doesn't show any details of these events (screenshot is attached). So it's necessary to develop a separate ListView or whatever to let user see all cool events of the day. 

Do you have in plans any default implementation of such list?

Many thanks in advance! 

![calendar_screenshot](https://github.com/user-attachments/assets/4afc667e-f63c-48ba-a7db-cfb6ba7c5909)

**Comment by yurkinh** [comment]
Hi @Rodionbar ,
There is already a list of events. It's just disabled by default. 

Enable/Disable the visibility of the Events scrollview panel at the bottom Sample properties:

`EventsScrollViewVisible="True"`

**Comment by MykhailoDav** [comment]
Hi @Rodionbar ,
Would you be kind enough to tell us if @yurkinh's answer helped you?

**Comment by Rodionbar** [comment]
Hi,

yes, it helped, and there are no more questions for now. The only suggestion is maybe to set EventsScrollViewVisible = "True" by default.

**Comment by yurkinh** [comment]
Hi @Rodionbar 
Initially, it was set to "true" but somebody has asked how to disable it? And can we set it to "false" by default))
To avoid confusion and just to get plain calendar I have disabled it ))
