### ISSUE TITLE
Can we use commands for Prev Next Year navigation events ?

### ISSUE THREAD

**Issue by praveenAnto** [yurkinh/Plugin.Maui.Calendar#90]
Like we are having commands for prev/next month navigations, do we have any events for year navigations ?

Ex for month navigation: **PrevLayoutUnitCommand & NextLayoutUnitCommand**

Also i want to reduce the height and width of cells and entire control height and width. When i am trying to change it cropping the cells. I am using Range selector calendar in windows.

**Comment by yurkinh** [comment]
Hi @praveenAnto 
Yes. There are: "PrevYearCommand" and "NextYearCommand"

**Comment by praveenAnto** [comment]
Thanks :)
