### ISSUE TITLE
The event indicator color has a black border

### ISSUE THREAD

**Issue by prok155** [yurkinh/Plugin.Maui.Calendar#93]
Recently I migrated my app from Xamarin to MAUI and I see that indicators has black border and I don't know how to get rid of it. Look at following screenshot:

![Screenshot_1728160219](https://github.com/user-attachments/assets/73dbd7eb-4260-49a8-8601-1dff89051478 )

As you can see, all indicators has black border. Could you tell me how to fix that? I couldn't find any samples, I also don't see any property like **EventIndicatorBorderColor**

**Comment by prok155** [comment]
I can also send you repo with above calendar if you need

**Comment by yurkinh** [comment]
Hi @prok155 
Yes. That would be very helpful

**Comment by prok155** [comment]
Unfortunately, I can't send the repo of this issue. 

When I create new project with the same plugin version (1.2.2) and the same calendar/viewmodel, indicators doesn't have black border. 

But when I paste this code to my client's app, indicators have black border, which is really wierd. 

[yurkinh](https://github.com/yurkinh) Do you have any idea why those black borders only appear in my client app? I don't see any property to change that color, and of course I can't send my client codebase to you...

I will still try to create repo of this issue.

**Comment by prok155** [comment]
Ok, after looking how this plugin works I know why this bug appears in my app. Indicators has black borders, because I have this style in App.xaml:


    <Style TargetType="Border">
                <Setter Property="Stroke"
                        Value="Black"/>
                <Setter Property="StrokeThickness"
                        Value="2"/>
                <Setter Property="Padding"
                        Value="20"/>
                <Setter Property="StrokeShape">
                    <RoundRectangle CornerRadius="10"/>
                </Setter>
            </Style>

When I remove this code from App.xaml, it solves my issue. 

I think that you should consider to set `StrokeThickness="0"` to the indicator border, it will fix this issue.

**Comment by MykhailoDav** [comment]
Hi @prok155,
Thank you for your suggestion, we will think about it, if we were able to help you with the issue and you are fully satisfied with our plugin, you can close the issue.
We appreciate you using our calendar!
