### ISSUE TITLE
Crash on iOS 18

### ISSUE THREAD

**Issue by marcustindab** [yurkinh/Plugin.Maui.Calendar#95]
Hey!

We recently updated our devices to iOS 18 and the app started to crash when displaying your calendar.

Works fine on iOS 17+

**Comment by yurkinh** [comment]
Hi @marcustindab 
I have not yet tested it with iOS 18 but this is due to the plugin not being updated to the latest MAUI version.
I will try to update it today and will submit a new version.
Also it would be very helpful to get some trace logs with exception

**Comment by marcustindab** [comment]
Unfortunately we don't have any exception logs to provide you with... We've tested this on a IPhone mini and a IPhone 15, both with iOS 18, and with the same crash.

**Comment by marcustindab** [comment]
@yurkinh 
Were you able to reproduce this?

**Comment by yurkinh** [comment]
Hi @marcustindab 
I was able to run successfully on ios simulator 18. Will try on my device after the update.
Also, we have new SR for the .net maui hence I will bump plugin to that latest one and republish.

**Comment by marcustindab** [comment]
@yurkinh 
After further investigation, we found out a probable release cause for this crash, related to this issue: 
https://github.com/dotnet/maui/issues/25139

I'm verifying this as we speak. Hopefully we can close this issue after our tests. Thank you so much for your quick responses so far!
