### ISSUE TITLE
New method to add any number to month or year of ShownDate

### ISSUE THREAD

**Issue by averlinghieri** [yurkinh/Plugin.Maui.Calendar#96]
Hello, thanks for the awesome library, I have implemented it successfully in a MAUI test app and I find it very useful.
I wanted to introduce the possibility for the user to pick a month or year from a list and the navigate to the picked month/year, the thing is if I just change the value of the parameter binding with ShownDate the calendar doesn't refresh its view; that seems to happen only if I use the Next/Prev commands, but those commands only move of 1 month or year per call.

I was wondering if it could be something worthy of being implemented since Next/Prev commands already exist, or if there already is a way and I just miss it.

**Comment by yurkinh** [comment]
Hi @averlinghieri 
Yes. Why not) Any new functionality that extends the existing one and does not break anything is very welcome)

**Comment by averlinghieri** [comment]
@yurkinh thanks for the reply! Shortly after I posted I realized I wasn't notifying the ShownDate property of changes and managed to achieve what I was trying to do, so if anyone find stuck on the same problem just make sure to have a NotifyPropertyChanged handler or use [ObservableProperty]
