### ISSUE TITLE
Missing some Controls 

### ISSUE THREAD

**Issue by yashaswinidc** [yurkinh/Plugin.Maui.Calendar#97]
I've noticed that several controls I was using in Xamarin.Forms, such as `SpecialDate`, `BackgroundPattern` and `Pattern` etc are missing in MAUI. These controls were available in the `XamForms.Controls` package. Are there any alternatives or similar controls available in MAUI that I can use? 

As the `Plugin.Maui.Calendar` serves as an equivalent replacement for these controls, I am currently checking its functionalities and implementation. If there are specific features or functionalities that I should pay attention to, please let me know!

**Comment by yashaswinidc** [comment]
@yurkinh Please help on this item.

**Comment by yurkinh** [comment]
Hi @yashaswinidc 
This calendar is a standalone control and was not a part of the mentioned package

**Comment by yashaswinidc** [comment]
Thank you for the response! Would it be possible to add these controls in the coming days, as I would like to implement similar functionality in calendar view?

**Comment by MykhailoDav** [comment]
Hi @yashaswinidc, we are currently working on the performance issues, this is a priority for us right now. 

However, you can become a part of the plugin and contribute to its growth by adding these controls, we will be very grateful!
